/*
 * This file was automatically generated by EvoSuite
 * Wed May 09 03:01:22 GMT 2018
 */

package com.company;

import org.junit.Test;
import static org.junit.Assert.*;
import com.company.Point;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Point_ESTest extends Point_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Point point0 = new Point(1, 1);
      assertEquals(1, point0.row);
      assertEquals(1, point0.col);
  }
}
